### PR TITLE
Fix small style issues reported by "brew audit"

### PR DESCRIPTION
**Pull request by jochenschneider**
Also added "brew audit" linting to the GitLab tests.

### CODE REVIEW

**Review by pattivacek — APPROVED** [review]
Nice, thanks for fixing this! I was just about to look into myself.

**Comment by pattivacek** [comment]
Why doesn't the triggered pipeline post the test result here? Oh well, it passed: https://main.gitlab.in.here.com/olp/edge/ota/connect/client/homebrew-otaconnect/pipelines/593414

**Comment by jochenschneider** [comment]
No idea. Does it do that for aktualizr?

**Comment by pattivacek** [comment]
> No idea. Does it do that for aktualizr?

Yeah, but I forgot if we had to do something special to set that up.

**Pull request merged**
