### PR TITLE
OTA-4594: use `make install` to copy build artifacts to prefix

### PR DESCRIPTION
**Pull request by mike-sul**
- `make install` instead of `cp` to copy build artifacts to the prefix directory
- don't install a bottle for the dev version
- make the aktualizr dev formula `head` and `keg_only`

Signed-off-by: Mykhaylo Sul <myk.sul@gmail.com>

### CODE REVIEW

**Comment by mike-sul** [comment]
Having the dev version as `keg_only` will allow a user to switch between a release version and current dev version of aktualizr by means `brew unlink <>` and `brew link <>`

`
17:02 $ brew link aktualizr
Linking /usr/local/Cellar/aktualizr/2020.2... 8 symlinks created
✔ ~ 
17:02 $ aktualizr --version
Current aktualizr version is: 2020.2-0-g56ac8da
✔ ~ 
17:02 $ brew unlink aktualizr
Unlinking /usr/local/Cellar/aktualizr/2020.2... 8 symlinks removed
✔ ~ 
17:02 $ brew link aktualizr-dev
Linking /usr/local/Cellar/aktualizr-dev/HEAD-0327762... 8 symlinks created
✔ ~ 
17:02 $ aktualizr --version
Current aktualizr version is: dev-0327762
✔ ~ 

`

**Review by pattivacek — COMMENTED** [review]
Looks fine to me, but I'm not sure how to test or lint. I'd like an ack from @tkfu or someone else who can verify.

**Comment by mike-sul** [comment]
> Looks fine to me, but I'm not sure how to test or lint. I'd like an ack from @tkfu or someone else who can verify.

I tested these two formulae on the mac we've got for CI.

**Review by tkfu — APPROVED** [review]
ACK

Tested locally on my mac, looks great, makes sense. Thanks!

**Pull request merged**
